project_id = "ueddnccouuevidwrcjaa"

[functions.print-orders]
verify_jwt = false

[functions.printer-orders]
verify_jwt = false

[functions.printer-config]
verify_jwt = false

[functions.printer-sync]
verify_jwt = false

[functions.nfce-emit]
verify_jwt = false

[functions.nfce-status]
verify_jwt = false

[functions.nfce-cancel]
verify_jwt = false